name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  codespell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          ignore_words_list: crate
          skip: ./.git

  validate-links:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby_version:
          - 3.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Install awesome_bot
        run: gem install awesome_bot

      - name: Validate URLs
        run: |
          awesome_bot ./*.md contracts/src/*.sol crates/eth_proof_backend/src/*.rs crates/eth_proofs/src/*.rs --allow-dupe --request-delay 0.4 \
          --allow-redirect -w https://github.com/user-attachments/assets/,http::StatusCode,http://localhost:3000/,https://opensource.org/license/mit
