name: Crates

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

jobs:
  check:
    name: Check crates
    runs-on: ubuntu-latest-16core-64ram
    defaults:
      run:
        working-directory: ./crates/

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "crates"
          cache-on-failure: true

      - name: Run fmt
        working-directory: crates
        run: |
          cargo fmt --all -- --check

      - name: Run build
        working-directory: crates
        run: cargo build --workspace --all-targets --all-features

      - name: Run clippy
        working-directory: crates
        run: cargo clippy --all-targets --all-features
